name: CatWeightLoss
options:
  bundleIdPrefix: com.catweightloss
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  CatWeightLoss:
    type: application
    platform: iOS
    sources:
      - path: CatWeightLoss
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: CatWeightLoss/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.catweightloss.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: "YES"
    info:
      path: CatWeightLoss/Info.plist
      properties:
        CFBundleDisplayName: Cat Weight Tracker
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSPhotoLibraryUsageDescription: "Add a photo of your cat."
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - catweighttracker
            CFBundleURLName: com.catweightloss.activate

  CatWeightLossTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CatWeightLossTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CatWeightLoss
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.catweightloss.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/CatWeightLoss.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/CatWeightLoss"
        BUNDLE_LOADER: "$(TEST_HOST)"
